"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const {MarketClient}=require("../src/engine/market-client.cjs");

test("erro 400 determinístico não percorre todos os hosts",async()=>{const original=global.fetch;let calls=0;global.fetch=async()=>{calls+=1;return{ok:false,status:400,headers:new Headers(),text:async()=>"bad"};};try{const client=new MarketClient({hosts:["https://a.test","https://b.test"]});await assert.rejects(()=>client.get("/bad"),/HTTP 400/);assert.equal(calls,1);}finally{global.fetch=original;}});

test("failover aprende host saudável e mede latência total",async()=>{const original=global.fetch,calls=[];global.fetch=async(url)=>{calls.push(url);if(url.startsWith("https://bad"))throw new Error("offline");return{ok:true,status:200,headers:new Headers(),json:async()=>({ok:true})};};try{const client=new MarketClient({hosts:["https://bad","https://good"],timeout:500,totalTimeout:2000});assert.deepEqual(await client.get("/ok",{},0),{ok:true});assert.equal(client.status().host,"https://good");await client.get("/next",{},0);assert.match(calls.at(-1),/^https:\/\/good/);assert.ok(client.status().totalLatencyMs>=0);}finally{global.fetch=original;}});

test("cache tem limite e force ignora valor anterior",async()=>{const original=global.fetch;let value=0;global.fetch=async()=>({ok:true,status:200,headers:new Headers(),json:async()=>({value:++value})});try{const client=new MarketClient({hosts:["https://ok"],cacheLimit:2});const first=await client.get("/a",{},10000);assert.deepEqual(await client.get("/a",{},10000),first);const forced=await client.get("/a",{},10000,{force:true});assert.notEqual(forced.value,first.value);await client.get("/b",{},10000);await client.get("/c",{},10000);assert.equal(client.status().cachedItems,2);}finally{global.fetch=original;}});

test("ticker usa um único snapshot e preço histórico nunca escolhe negócio após o vencimento",async()=>{const original=global.fetch,calls=[];global.fetch=async(url)=>{calls.push(url);if(url.includes("ticker/24hr"))return{ok:true,status:200,headers:new Headers(),json:async()=>({lastPrice:"100",bidPrice:"99",askPrice:"101"})};return{ok:true,status:200,headers:new Headers(),json:async()=>[{p:"102",T:1001,a:2},{p:"99",T:999,a:1}]};};try{const clock={now:()=>1100,status:()=>({})};const client=new MarketClient({hosts:["https://ok"],clock});const ticker=await client.ticker("BTCUSDT");assert.equal(ticker.last,100);assert.equal(calls.length,1);const historical=await client.priceAt("BTCUSDT",1000,{toleranceMs:10});assert.equal(historical.value,99);assert.equal(historical.exchangeTimestamp,999);assert.match(calls.at(-1),/endTime=1000/);}finally{global.fetch=original;}});
