"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const EventEmitter=require("node:events");const {RealtimeHub}=require("../src/engine/realtime-hub.cjs");

class FakeSocket extends EventEmitter{static CONNECTING=0;static OPEN=1;static CLOSED=3;static instances=[];constructor(url){super();this.url=url;this.readyState=FakeSocket.CONNECTING;FakeSocket.instances.push(this);}open(){this.readyState=FakeSocket.OPEN;this.emit("open");}message(value){this.emit("message",Buffer.from(JSON.stringify(value)));}close(){this.readyState=FakeSocket.CLOSED;this.emit("close");}terminate(){this.close();}}
const clock={now:()=>1_800_000_000_000,status:()=>({synced:true})};

test("mensagem de socket antigo não contamina novo ativo",()=>{FakeSocket.instances=[];const hub=new RealtimeHub({streamHosts:["wss://test"],WebSocketImpl:FakeSocket,clock});try{hub.start();const old=FakeSocket.instances[1];old.open();hub.select("ETHUSDT","1m");const current=FakeSocket.instances.at(-1);current.open();old.message({stream:"btcusdt@aggTrade",data:{e:"aggTrade",s:"BTCUSDT",a:1,T:clock.now(),p:"50000",q:"1",m:false}});assert.equal(hub.snapshot().symbol,"ETHUSDT");assert.equal(hub.snapshot().ticker,null);current.message({stream:"ethusdt@aggTrade",data:{e:"aggTrade",s:"ETHUSDT",a:2,T:clock.now(),p:"2000",q:"2",m:false}});assert.equal(hub.priceDatums().ETHUSDT.value,2000);assert.equal(hub.priceDatums().BTCUSDT,undefined);}finally{hub.close();}});

test("aggTrade duplicado não altera fluxo duas vezes",()=>{FakeSocket.instances=[];const hub=new RealtimeHub({streamHosts:["wss://test"],WebSocketImpl:FakeSocket,clock});try{hub.start();const socket=FakeSocket.instances[1];socket.open();const event={stream:"btcusdt@aggTrade",data:{e:"aggTrade",s:"BTCUSDT",a:9,T:clock.now(),p:"100",q:"3",m:false}};socket.message(event);socket.message(event);assert.equal(hub.snapshot().flow.buyVolume,3);assert.equal(hub.snapshot().connection.duplicateTrades,1);}finally{hub.close();}});

test("snapshot do scanner não permite mutar estado interno",()=>{FakeSocket.instances=[];const hub=new RealtimeHub({streamHosts:["wss://test"],WebSocketImpl:FakeSocket,clock});try{hub.start();const market=FakeSocket.instances[0];market.open();market.message([{s:"BTCUSDT",c:"100",o:"90",h:"105",l:"85",v:"2",q:"200",E:clock.now()}]);const first=hub.marketSnapshot();first[0].last=0;assert.equal(hub.marketSnapshot()[0].last,100);}finally{hub.close();}});

test("eventos futuros são rejeitados e scanner publica preços de todos os pares",()=>{FakeSocket.instances=[];const hub=new RealtimeHub({streamHosts:["wss://test"],WebSocketImpl:FakeSocket,clock});const seen=[];hub.on("market-price",datum=>seen.push(datum));try{hub.start();const market=FakeSocket.instances[0],symbol=FakeSocket.instances[1];market.open();symbol.open();market.message([{s:"BTCUSDT",c:"100",o:"90",h:"105",l:"85",v:"2",q:"200",E:clock.now()},{s:"ETHUSDT",c:"20",o:"19",h:"21",l:"18",v:"3",q:"60",E:clock.now()}]);assert.deepEqual(new Set(seen.map(x=>x.symbol)),new Set(["BTCUSDT","ETHUSDT"]));symbol.message({stream:"btcusdt@aggTrade",data:{e:"aggTrade",s:"BTCUSDT",a:10,T:clock.now()+5000,p:"999",q:"1",m:false}});assert.notEqual(hub.snapshot().ticker?.last,999);assert.ok(hub.snapshot().connection.rejectedTimestamps>=1);}finally{hub.close();}});
