"use strict";

const state = { token:"", symbol:"BTCUSDT", interval:"15m", coins:[], live:null, analysis:null, paper:null, calibration:null, health:null, signals:[], signalHistory:[], alerts:[], journal:[], journalPage:{total:0,offset:0,limit:25,hasMore:false,query:""}, side:"buy", eventSource:null, chartFrame:null, chartZoom:120, chartOffset:0, chartFollow:true, chartCrosshair:null, chartDrag:null, chartMetrics:null, chartTool:null, chartDraft:null, chartDrawings:[], lastResultId:null, paperSignature:"", selectionGeneration:0, analysisGeneration:0, analysisController:null, aiGeneration:0, settingsReturnFocus:null, storageWarningShown:false };
const $ = (id) => document.getElementById(id);
const esc = (v) => String(v ?? "").replace(/[&<>'"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const fmt = (v, max=8) => Number.isFinite(Number(v)) ? new Intl.NumberFormat("pt-BR",{maximumFractionDigits:max}).format(Number(v)) : "--";
const money = (v) => Number.isFinite(Number(v)) ? new Intl.NumberFormat("pt-BR",{style:"currency",currency:"USD"}).format(Number(v)) : "--";
const pct = (v,d=2) => Number.isFinite(Number(v)) ? `${Number(v)>=0?"+":""}${Number(v).toFixed(d)}%` : "--";
const api = async (url, options={}) => {
  const timeoutMs=Number(options.timeoutMs)||15000,controller=new AbortController(),timer=setTimeout(()=>controller.abort(new DOMException("Tempo limite excedido.","TimeoutError")),timeoutMs),external=options.signal;
  if(external){if(external.aborted)controller.abort(external.reason);else external.addEventListener("abort",()=>controller.abort(external.reason),{once:true});}
  const headers={"X-Dief-Token":state.token,...options.headers};if(options.body!=null&&!headers["Content-Type"])headers["Content-Type"]="application/json";
  const request={...options,headers,signal:controller.signal};delete request.timeoutMs;
  let res;try{res=await fetch(url,request);}catch(error){if(external?.aborted){const cancelled=new Error("Solicitação cancelada.");cancelled.name="AbortError";throw cancelled;}if(controller.signal.aborted)throw new Error("O serviço demorou demais para responder.");throw error;}finally{clearTimeout(timer);}
  const data = await res.json().catch(()=>({error:`HTTP ${res.status}`}));
  if(!res.ok){const error=new Error(data.error||`Falha ${res.status}`);error.code=data.code;error.status=res.status;throw error;}
  return data;
};
const toast = (message,error=false) => { const el=$("toast"); el.textContent=message; el.className=`toast show${error?" error":""}`; clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.className="toast",3200); };
const priceFormat = (v) => { const n=Number(v); if(!Number.isFinite(n)) return "--"; const digits=n>=1000?2:n>=1?4:n>=.01?6:8; return `$${fmt(n,digits)}`; };

function readToken(){const fragment=new URLSearchParams(location.hash.replace(/^#/,""));const supplied=fragment.get("t");if(supplied)sessionStorage.setItem("dieftrade.session",supplied);state.token=supplied||sessionStorage.getItem("dieftrade.session")||"";if(supplied)history.replaceState(null,"",`${location.pathname}${location.search}`);}
function clock(){ $("clock").textContent=new Date().toLocaleTimeString("pt-BR"); }
function setConnection(online,text){ $("pulse").className=`pulse ${online?"online":"offline"}`; $("connection").textContent=text; }
async function refreshHealth(silent=false){
  try{
    state.health=await api("/api/health");state.calibration=state.health.calibration||state.calibration;
    const h=state.health,live=h.live||{},market=h.market||{},labels={paper:"Simulador",alerts:"Alertas",journal:"Diário",calibration:"Calibração",signals:"Sinais"};
    const storageIssues=Object.entries(h.persistence||{}).flatMap(([area,diagnostic])=>(diagnostic?.issues||[]).map(issue=>({area:labels[area]||area,recovered:Boolean(issue.recovery?.source)})));
    const aiState=h.ai?.configured?(h.ai.migrationRequired?"MIGRAÇÃO NECESSÁRIA":h.ai.telemetry?.lastDiagnostic?.ok?"geração validada":"aguardando diagnóstico"):"opcional / não configurada";const monitorHealthy=Number(h.alertMonitor?.oldestCheckAgeMs||0)<60000;
    const items=[["Versão",h.version,true],["Fluxo ao vivo",live.connected&&!live.stale?"saudável":"reconectando",live.connected&&!live.stale],["Latência REST",market.latencyMs==null?"aguardando":`${market.latencyMs} ms`,market.latencyMs!=null&&market.latencyMs<1500],["Failovers",market.failovers||0,(market.failovers||0)<5],["IA",aiState,!h.ai?.migrationRequired],["Ciclo de sinais",`${h.signalLifecycle?.active||0} ativo(s) · ${h.signalLifecycle?.confirmed||0} confirmado(s)`,true],["Calibração geral",`${h.calibration?.samples||0} amostras · ${h.calibration?.learning||"aquecendo"}`,true],["Alertas técnicos",`${h.alertMonitor?.activeTargets||0} alvo(s) · atraso máx. ${Math.round(Number(h.alertMonitor?.oldestCheckAgeMs||0)/1000)} s`,monitorHealthy],["Memória",`${h.memory?.rssMb||"--"} MB`,Number(h.memory?.rssMb||0)<500],["Ordens reais",h.safety?.realOrders?"ATIVAS":"desativadas",!h.safety?.realOrders]];
    if(storageIssues.length)items.push(["Recuperação local",storageIssues.map(item=>`${item.area}: ${item.recovered?"backup restaurado":"dados reiniciados"}`).join(" · "),false]);else items.push(["Arquivos locais","íntegros",true]);
    $("healthGrid").innerHTML=items.map(([label,value,ok])=>`<div class="health-item ${ok?"ok":"warn"}"><span>${esc(label)}</span><b>${esc(value)}</b></div>`).join("");
    if(storageIssues.length&&!state.storageWarningShown){state.storageWarningShown=true;toast("Um arquivo local precisou ser recuperado. Veja Saúde do painel.",true);}else if(!silent)toast("Diagnóstico atualizado");
  }catch(error){if(!silent)toast(error.message,true);}
}

async function bootstrap(){
  readToken(); applyPreferences(); clock(); setInterval(clock,1000);
  bind();
  try{
    let data,lastError;for(let attempt=0;attempt<4;attempt+=1){try{data=await api("/api/bootstrap",{timeoutMs:20000});break;}catch(error){lastError=error;if(attempt<3)await new Promise(resolve=>setTimeout(resolve,400*2**attempt));}}if(!data)throw lastError;
    state.coins=data.coins||[]; state.symbol=data.selected.symbol; state.interval=data.selected.interval; state.paper=data.paper; state.calibration=data.calibration||null; state.signals=data.signals||[]; state.alerts=data.alerts||[]; const journalPage=Array.isArray(data.journal)?{items:data.journal,total:data.journal.length,offset:0,limit:25,hasMore:false,query:""}:data.journal||{};state.journal=journalPage.items||[];state.journalPage={...state.journalPage,...journalPage};state.lastResultId=state.paper?.results?.[0]?.id||"__empty__";state.paperSignature=paperSignature(state.paper);loadDrawings();
    $("aiProvider").value=data.ai?.provider||"gemini";$("aiModel").value=data.ai?.model||($("aiProvider").value==="gemini"?"gemini-2.5-flash":"gpt-5");
    $("aiStatus").textContent=data.ai?.configured?(data.ai.migrationRequired?`⚠ Chave ${data.ai.keyType} preservada · migre para Auth AQ.`:`Chave protegida · ${data.ai.provider==="gemini"?"Gemini":"OpenAI"} · ${data.ai.model}`):"IA ainda não configurada";
    renderCoins(); renderPaper(); renderAlerts(); renderJournal(); updateSelection(); connectStream();updateAlertValue();void refreshHealth(true);
    await refreshAnalysis();
    setInterval(refreshCoins,10000); setInterval(()=>refreshAnalysis(true),6500);setInterval(refreshPaper,2000);setInterval(updatePaperCountdowns,250);setInterval(updateAnalysisFreshness,1000);setInterval(()=>refreshHealth(true),15000);
  }catch(error){ setConnection(false,"falha local"); toast(error.message,true); }
}

function bind(){
  $("coinSearch").addEventListener("input",renderCoins);
  $("intervals").addEventListener("click",async(e)=>{const b=e.target.closest("button[data-i]");if(!b||b.dataset.i===state.interval)return;const previous=state.interval;state.interval=b.dataset.i;await selectMarket({previousInterval:previous});});
  $("tabs").addEventListener("click",(e)=>{const b=e.target.closest("button[data-tab]");if(!b)return;document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".tab-page").forEach(x=>x.classList.toggle("active",x.id===`tab-${b.dataset.tab}`));if(b.dataset.tab==="reading")drawChart();});
  document.querySelectorAll(".side-toggle button").forEach(b=>b.addEventListener("click",()=>{state.side=b.dataset.side;document.querySelectorAll(".side-toggle button").forEach(x=>x.classList.toggle("active",x===b));}));
  document.querySelectorAll(".side-toggle button").forEach(b=>b.addEventListener("click",updateOrderPreview));
  $("paperQty").addEventListener("input",updateOrderPreview);$("paperExpiry").addEventListener("change",updateOrderPreview);
  document.querySelectorAll(".quick-values button").forEach(b=>b.addEventListener("click",()=>{$("paperQty").value=b.dataset.value;updateOrderPreview();}));
  $("paperForm").addEventListener("submit",submitPaper); $("alertForm").addEventListener("submit",submitAlert); $("journalForm").addEventListener("submit",submitJournal); $("aiForm").addEventListener("submit",saveAi); $("removeAi").addEventListener("click",removeAi); $("aiRead").addEventListener("click",readAi);$("aiTest").addEventListener("click",testAi);
  $("journalSearch").addEventListener("input",()=>{clearTimeout(state.journalSearchTimer);state.journalSearchTimer=setTimeout(()=>loadJournal({offset:0,query:$("journalSearch").value}),250);});$("journalPrev").addEventListener("click",()=>loadJournal({offset:Math.max(0,state.journalPage.offset-state.journalPage.limit)}));$("journalNext").addEventListener("click",()=>loadJournal({offset:state.journalPage.offset+state.journalPage.limit}));
  $("resetPaper").addEventListener("click",resetPaper);$("exportPaper").addEventListener("click",exportPaper);$("paperPayout").addEventListener("change",savePaperSettings);$("alertKind").addEventListener("change",updateAlertValue);$("aiProvider").addEventListener("change",()=>setAiProviderDefaults(true));
  $("openSettings").addEventListener("click",()=>{state.settingsReturnFocus=document.activeElement;$("settingsModal").classList.add("open");$("settingsModal").setAttribute("aria-hidden","false");$("closeSettings").focus();void refreshHealth();}); $("closeSettings").addEventListener("click",closeSettings); $("settingsModal").addEventListener("click",e=>{if(e.target===$("settingsModal"))closeSettings();});
  $("themeGrid").addEventListener("click",e=>{const b=e.target.closest("[data-theme]");if(!b)return;savePreference("theme",b.dataset.theme);applyPreferences();});
  $("uiScale").addEventListener("change",e=>{savePreference("scale",e.target.value);applyPreferences();}); $("reduceMotion").addEventListener("change",e=>{savePreference("reduceMotion",e.target.checked);applyPreferences();});$("alertSound").addEventListener("change",e=>{savePreference("alertSound",e.target.checked);applyPreferences();});$("refreshHealth").addEventListener("click",()=>refreshHealth());
  $("chartFollow").addEventListener("click",()=>setChartView(0,state.chartZoom,true));$("chartOlder").addEventListener("click",()=>setChartView(state.chartOffset+Math.max(10,Math.round(state.chartZoom/5)),state.chartZoom,false));$("chartZoomIn").addEventListener("click",()=>setChartView(state.chartOffset,Math.max(30,state.chartZoom-20),state.chartFollow));$("chartZoomOut").addEventListener("click",()=>setChartView(state.chartOffset,Math.min(260,state.chartZoom+20),state.chartFollow));$("chartReset").addEventListener("click",()=>setChartView(0,120,true));$("chartHorizontal").addEventListener("click",()=>setChartTool("horizontal"));$("chartTrend").addEventListener("click",()=>setChartTool("trend"));$("chartClear").addEventListener("click",clearDrawings);
  const chart=$("chart");chart.addEventListener("wheel",e=>{e.preventDefault();setChartView(state.chartOffset,Math.max(30,Math.min(260,state.chartZoom+(e.deltaY>0?20:-20))),state.chartFollow);},{passive:false});chart.addEventListener("pointerdown",chartPointerDown);chart.addEventListener("pointermove",chartPointerMove);chart.addEventListener("pointerup",()=>{state.chartDrag=null;});chart.addEventListener("pointercancel",()=>{state.chartDrag=null;});chart.addEventListener("pointerleave",()=>{if(!state.chartDrag){state.chartCrosshair=null;$("chartTooltip").style.display="none";requestChart();}});
  window.addEventListener("resize",()=>requestAnimationFrame(drawChart));
  document.addEventListener("keydown",e=>{if(e.key==="Escape"&&$("settingsModal").classList.contains("open"))closeSettings();});
}

function requestChart(){if(state.chartFrame)cancelAnimationFrame(state.chartFrame);state.chartFrame=requestAnimationFrame(drawChart);}
function setChartView(offset,zoom,follow=false){const max=Math.max(0,(state.analysis?.series?.candles?.length||0)-30);state.chartOffset=Math.max(0,Math.min(max,Number(offset)||0));state.chartZoom=Math.max(30,Math.min(260,Number(zoom)||120));state.chartFollow=Boolean(follow&&state.chartOffset===0);$("chartFollow").classList.toggle("active",state.chartFollow);requestChart();}
function setAiProviderDefaults(force=false){const provider=$("aiProvider").value,target=provider==="gemini"?"gemini-2.5-flash":"gpt-5";if(force||!$("aiModel").value.trim())$("aiModel").value=target;$("aiKey").placeholder=provider==="gemini"?"Cole a chave do Google AI Studio":"Cole a chave da OpenAI";}

function closeSettings(){$("settingsModal").classList.remove("open");$("settingsModal").setAttribute("aria-hidden","true");state.settingsReturnFocus?.focus?.();}
function preferences(){try{const value=JSON.parse(localStorage.getItem("dieftrade.preferences")||"{}");return value&&typeof value==="object"&&!Array.isArray(value)?value:{};}catch{return {};}}
function savePreference(key,value){const allowed={theme:new Set(["dief","terminal","midnight","light","graphite"]),scale:new Set(["compact","normal","comfortable"]),reduceMotion:new Set([true,false]),alertSound:new Set([true,false])};if(!allowed[key]?.has(value))return;const prefs=preferences();prefs[key]=value;try{localStorage.setItem("dieftrade.preferences",JSON.stringify(prefs));}catch{toast("Não foi possível salvar a preferência.",true);}}
function applyPreferences(){const prefs=preferences(),theme=["dief","terminal","midnight","light","graphite"].includes(prefs.theme)?prefs.theme:"dief",scale=["compact","normal","comfortable"].includes(prefs.scale)?prefs.scale:"normal";document.body.dataset.theme=theme;document.body.dataset.scale=scale;document.body.classList.toggle("reduce-motion",Boolean(prefs.reduceMotion));if($("themeGrid"))document.querySelectorAll(".theme-choice").forEach(x=>x.classList.toggle("active",x.dataset.theme===theme));if($("uiScale"))$("uiScale").value=scale;if($("reduceMotion"))$("reduceMotion").checked=Boolean(prefs.reduceMotion);if($("alertSound"))$("alertSound").checked=prefs.alertSound!==false;setTimeout(()=>{drawChart();drawPaperEquity();},30);}

async function refreshCoins(){try{state.coins=await api("/api/coins?limit=220");renderCoins();}catch(error){console.warn("Falha ao atualizar pares:",error.message);}}
function renderCoins(){
  const q=$("coinSearch").value.trim().toUpperCase(); const rows=state.coins.filter(c=>!q||c.symbol.includes(q)||c.base?.includes(q));
  $("coinCount").textContent=rows.length; $("coinList").innerHTML=rows.map(c=>`<button type="button" class="coin-row ${c.symbol===state.symbol?"active":""}" data-symbol="${esc(c.symbol)}" aria-label="Selecionar ${esc(c.symbol)}"><span><b>${esc(c.base||c.symbol.replace("USDT",""))}</b><small>/ USDT</small></span><span class="last">${priceFormat(c.last).slice(1)}</span><b class="${Number(c.changePct)>=0?"positive":"negative"}">${pct(c.changePct)}</b></button>`).join("")||`<p class="legal">Nenhum par encontrado.</p>`;
  $("coinList").querySelectorAll("[data-symbol]").forEach(row=>row.addEventListener("click",async()=>{const previous=state.symbol;state.symbol=row.dataset.symbol;await selectMarket({previousSymbol:previous});}));
}
async function selectMarket({previousSymbol=null,previousInterval=null}={}){
  const generation=++state.selectionGeneration;state.analysisController?.abort();state.analysis=null;state.live=null;$("aiResult").textContent="A leitura de IA será limpa ao mudar de mercado.";
  state.chartOffset=0;state.chartFollow=true;state.chartCrosshair=null;state.chartDraft=null;loadDrawings();
  updateSelection(); renderCoins(); $("chartEmpty").style.display="grid"; $("chartEmpty").textContent="Atualizando a leitura…";
  try{await api("/api/live/select",{method:"POST",body:JSON.stringify({symbol:state.symbol,interval:state.interval})});if(generation!==state.selectionGeneration)return;connectStream();await refreshAnalysis();}catch(error){if(generation!==state.selectionGeneration)return;if(previousSymbol)state.symbol=previousSymbol;if(previousInterval)state.interval=previousInterval;updateSelection();renderCoins();toast(error.message,true);}
}
function updateSelection(){
  const base=state.symbol.replace(/USDT$/,""); $("symbol").textContent=`${base}/USDT`; $("coinMark").textContent=base==="BTC"?"₿":base.slice(0,2); document.querySelectorAll("#intervals button").forEach(b=>b.classList.toggle("active",b.dataset.i===state.interval));
}
function connectStream(){
  state.eventSource?.close(); const es=new EventSource(`/api/live/stream?t=${encodeURIComponent(state.token)}`); state.eventSource=es;
  es.addEventListener("ready",()=>setConnection(false,"serviço local conectado · aguardando mercado"));
  es.addEventListener("snapshot",event=>{try{const next=JSON.parse(event.data);if(next.symbol&&next.symbol!==state.symbol)return;state.live=next;renderLive();}catch(error){console.warn("Snapshot inválido:",error.message);}});
  es.addEventListener("market",event=>{try{const next=JSON.parse(event.data);if(Array.isArray(next)){state.coins=next;renderCoins();}}catch(error){console.warn("Mercado inválido:",error.message);}});
  es.addEventListener("coins",event=>{try{const next=JSON.parse(event.data);if(!Array.isArray(next))throw new Error("lista inválida");state.coins=next;renderCoins();}catch(error){console.warn("Lista de pares inválida:",error.message);}});
  es.addEventListener("alert",event=>{try{const alert=JSON.parse(event.data);notifyAlert(alert);state.alerts=state.alerts.map(item=>item.id===alert.id?alert:item);renderAlerts();}catch(error){console.warn("Alerta inválido:",error.message);}});
  es.addEventListener("paper-result",event=>{try{const result=JSON.parse(event.data);if(!result?.id)throw new Error("resultado sem identificação");if(result.id!==state.lastResultId){state.lastResultId=result.id;notifyPaperResult(result);}void refreshPaper();}catch(error){console.warn("Resultado inválido:",error.message);}});
  ["signal-candidate","signal-confirmed","signal-weakened","signal-invalidated","signal-suspended","signal-resumed","signal-candidate-cancelled"].forEach(type=>es.addEventListener(type,event=>{try{const item=JSON.parse(event.data);state.signalHistory=[item,...state.signalHistory.filter(row=>row.eventId!==item.eventId)].slice(0,100);void refreshSignals();if(type==="signal-confirmed")toast(`${item.direction} confirmada em ${priceFormat(item.confirmedPrice)}`);}catch(error){console.warn("Evento de sinal inválido:",error.message);}}));
  es.onerror=()=>setConnection(false,"reconectando…");
}
function renderLive(){
  const l=state.live;if(!l)return; setConnection(Boolean(l.connected&&!l.stale),l.stale?"dados atrasados":"mercado ao vivo");
  if(l.ticker?.last) $("price").textContent=priceFormat(l.ticker.last);
  const coin=state.coins.find(c=>c.symbol===state.symbol); if(coin){$("change").textContent=pct(coin.changePct);$("change").className=coin.changePct>=0?"positive":"negative";}else{$("change").textContent="--";$("change").className="";}
  const ratio=Number(l.flow?.buyRatio); $("buyRatio").textContent=Number.isFinite(ratio)?`${(ratio*100).toFixed(1)}%`:"--"; $("buySplit").style.width=`${(Number.isFinite(ratio)?ratio:.5)*100}%`;
  const imb=Number(l.book?.imbalance); $("imbalance").textContent=Number.isFinite(imb)?`${(imb*100).toFixed(1)}%`:"--"; $("bookSplit").style.width=`${(Number.isFinite(imb)?imb:.5)*100}%`;
  $("spread").textContent=pct(l.ticker?.spreadPct,4); const unit=state.symbol.replace(/USDT$/,'');$("delta").textContent=Number.isFinite(Number(l.flow?.deltaQuote))?`Delta: ${money(l.flow.deltaQuote)} · ${fmt(l.flow?.delta,4)} ${unit}`:`Delta: ${fmt(l.flow?.delta,4)} ${unit}`; renderBook(l.book);renderTape(l.trades);
  mergeLiveCandle(l.candle);
}
function mergeLiveCandle(candle){if(!candle||!state.analysis?.series?.candles?.length)return;state.provisionalCandle={...candle,provisional:!candle.closed};requestChart();}
function renderBook(book={}){
  const side=(rows,kind)=>{const max=Math.max(...(rows||[]).map(x=>x[1]),1);return `<div class="book-side ${kind}">${(rows||[]).slice(0,12).map(([p,q])=>`<div class="book-row" style="--depth:${Math.max(4,q/max*100)}%"><span class="${kind==="ask"?"negative":"positive"}">${fmt(p,8)}</span><span>${fmt(q,5)}</span></div>`).join("")}</div>`};
  $("book").innerHTML=side(book.bids,"bid")+side(book.asks,"ask");
}
function renderTape(trades=[]){const unit=state.symbol.replace(/USDT$/,'');$("tape").innerHTML=(trades||[]).slice(0,35).map(t=>`<div class="tape-row"><b class="${t.side==="buy"?"positive":"negative"}">${t.side==="buy"?"COMPRA":"VENDA"}</b><span>${fmt(t.price,8)}</span><span title="Quantidade em ${esc(unit)}">${fmt(t.quantity,5)} ${esc(unit)}</span><time>${Number.isFinite(Number(t.t))?new Date(Number(t.t)).toLocaleTimeString("pt-BR"):"--"}</time></div>`).join("")||`<p class="legal">Aguardando negócios…</p>`;}

async function refreshAnalysis(silent=false){
  const symbol=state.symbol,interval=state.interval,generation=++state.analysisGeneration;state.analysisController?.abort();const controller=new AbortController();state.analysisController=controller;
  try{const a=await api(`/api/analysis/${symbol}?interval=${interval}`,{signal:controller.signal,timeoutMs:25000});if(generation!==state.analysisGeneration||symbol!==state.symbol||interval!==state.interval)return;state.analysis={...a,receivedAt:Date.now()};renderAnalysis();void refreshSignals();if(!silent){$("chartEmpty").style.display="none";}}
  catch(error){if(error.name!=="AbortError"&&generation===state.analysisGeneration&&!silent)toast(error.message,true);}
}
function renderAnalysis(){
  const a=state.analysis;if(!a)return;if(!(state.live?.ticker?.last>0))$("price").textContent=priceFormat(a.price); $("signal").textContent=a.signal;$("signal").className=`signal ${a.signal==="COMPRA"?"buy":a.signal==="VENDA"?"sell":""}`; $("regime").textContent=a.regime; $("confidence").textContent=`${a.confidence}%`;$("confidenceBar").style.width=`${a.confidence}%`;$("score").textContent=a.score>0?`+${a.score}`:a.score;$("scoreDot").style.left=`calc(${Math.max(0,Math.min(100,(a.score+100)/2))}% - 5px)`;
  renderSignalLifecycle(a.signalLifecycle);
  const mt=a.multiTimeframe||{};$("alignment").textContent=`${mt.alignment??0}% · ${mt.available??0}/${mt.expected??0}`;const frames=mt.frames||{},frameOrder=Object.keys(frames).length?Object.keys(frames):["1m","5m","15m","1h","4h"];$("frames").innerHTML=frameOrder.map(f=>{const v=frames[f];return `<i title="${f}: ${esc(v?.signal||"indisponível")} · score ${esc(v?.score??"--")} · qualidade ${esc(v?.dataQuality??"--")} · ${esc(v?.regime||"")}" class="${v?.signal==="COMPRA"?"buy":v?.signal==="VENDA"?"sell":""}"></i>`;}).join("");
  $("reasons").innerHTML=(a.reasons||[]).map(r=>`<div class="reason ${r.points<0?"negative-reason":""}"><span class="dir">${r.points>0?"↗":r.points<0?"↘":"•"}</span><span><b>${esc(r.text||r.label||r.reason)}</b>${r.detail?`<small>${esc(r.detail)}</small>`:""}</span><b>${r.points>0?"+":""}${r.points}</b></div>`).join("");
  const labels={rsi:"RSI 14",macd:"MACD",macdSignal:"Sinal MACD",macdHistogram:"MACD hist.",adx:"ADX",atr:"ATR",atrPct:"ATR %",volumeRatio:"Volume",stochasticK:"Estocástico K",stochasticD:"Estocástico D",ema9:"EMA 9",ema20:"EMA 20",ema50:"EMA 50",ema200:"EMA 200",vwap:"VWAP",bollingerUpper:"Bollinger sup.",bollingerMiddle:"Bollinger média",bollingerLower:"Bollinger inf.",bollingerPercentB:"Bollinger %B",bandwidth:"Bandwidth",obvSlope:"Inclinação OBV",roc:"ROC"};
  $("indicators").innerHTML=Object.entries(labels).map(([k,l])=>`<div class="data-item"><span>${l}</span><b>${fmt(a.indicators?.[k],k.includes("ema")||k==="vwap"?8:3)}</b></div>`).join("");
  $("warnings").innerHTML=(a.warnings||[]).map(w=>`<p>• ${esc(w)}</p>`).join("")||"<p>• Nenhum aviso automático adicional; risco de mercado continua existindo.</p>";
  const quality=a.dataQuality||{};$("dataQuality").textContent=`${quality.score??"--"}/100`;$("dataQualityDetail").textContent=`Atualidade ${quality.freshness??"--"} · liquidez ${quality.liquidity??"--"} · ${quality.lastCandleClosed===false?"vela atual ainda aberta":"vela confirmada"}.`;
  const calibration=a.calibration||{},pairSamples=Number(calibration.pairSamples??calibration.samples??0),applied=Boolean(calibration.applied);$("calibrationScore").textContent=applied?"MADURO":String(calibration.state||"aquecendo").toUpperCase();$("calibrationDetail").textContent=pairSamples?`${pairSamples} sinal(is) confirmado(s) avaliados em ${a.symbol}/${a.interval} · ${applied?"pesos adaptativos aplicados":"ainda em aquecimento"} · confiabilidade suavizada ${fmt(Number(calibration.reliability)*100,1)}%.`:"Este par e timeframe ainda não possuem sinais confirmados avaliados no horizonte correto.";
  updateAnalysisFreshness();renderPlan(a.plan);renderLevels(a.levels);updatePixel();updateOrderPreview();drawChart();
}
function signalStatusLabel(s){const labels={NEUTRAL:"NEUTRO",CANDIDATE_BUY:"CANDIDATO A COMPRA",CANDIDATE_SELL:"CANDIDATO A VENDA",CONFIRMED_BUY:"COMPRA CONFIRMADA",CONFIRMED_SELL:"VENDA CONFIRMADA",WEAKENING_BUY:"COMPRA ENFRAQUECENDO",WEAKENING_SELL:"VENDA ENFRAQUECENDO",INVALIDATED:"SINAL INVALIDADO",SUSPENDED_DATA:"DADOS ATRASADOS"};return labels[s?.status]||"NEUTRO";}
function renderSignalLifecycle(s){const el=$("confirmedSignal"),detail=$("confirmedSignalDetail");if(!el||!detail)return;el.textContent=signalStatusLabel(s);el.className=`signal ${s?.direction==="COMPRA"?"buy":s?.direction==="VENDA"?"sell":""}`;if(/^CANDIDATE_/.test(s?.status||"")){detail.textContent=`Confirmação em andamento · ${s.consistentEvaluations||1} avaliação(ões) consistente(s).`;return;}if(s?.signalId){const confirmed=new Date(Number(s.confirmedAt)).toLocaleTimeString("pt-BR",{fractionalSecondDigits:3});const invalid=s.invalidatedAt?` · invalidado ${new Date(Number(s.invalidatedAt)).toLocaleTimeString("pt-BR")}: ${s.invalidationReason||"condição perdida"}`:"";detail.textContent=`${confirmed} · ${priceFormat(s.confirmedPrice)} · ${s.interval}${invalid}`;return;}detail.textContent=s?.status==="SUSPENDED_DATA"?"Sinal preservado; validação realtime suspensa até os dados voltarem.":"Aguardando condições estáveis e preço ao vivo.";}
async function refreshSignals(){try{const [current,history]=await Promise.all([api(`/api/signals/current?symbol=${state.symbol}&interval=${state.interval}`),api(`/api/signals/history?symbol=${state.symbol}&interval=${state.interval}&limit=100`)]);state.signals=current;state.signalHistory=history;const active=current[0]||state.analysis?.signalLifecycle;renderSignalLifecycle(active);renderSignalHistory();}catch(error){console.warn("Falha ao atualizar sinais:",error.message);}}
function renderSignalHistory(){const labels={"signal-candidate":"candidato","signal-confirmed":"confirmado","signal-weakened":"enfraquecendo","signal-invalidated":"invalidado","signal-suspended":"suspenso por dados","signal-resumed":"retomado","signal-candidate-cancelled":"candidato cancelado"};$("signalHistory").innerHTML=(state.signalHistory||[]).map(event=>`<div class="list-row"><span><b class="${event.direction==="COMPRA"?"positive":event.direction==="VENDA"?"negative":""}">${esc(event.direction||"SINAL")}</b> · ${esc(labels[event.type]||event.type)}<br><small>${new Date(Number(event.at)).toLocaleString("pt-BR")}${event.confirmedPrice?` · ${priceFormat(event.confirmedPrice)}`:""}${event.reason?` · ${esc(event.reason)}`:""}</small></span><small>${event.signalId?esc(event.signalId.slice(0,8)):"—"}</small></div>`).join("")||`<p class="legal">Nenhum evento confirmado para este mercado.</p>`;}
function updateAnalysisFreshness(){const badge=$("staleBadge");if(!badge)return;const age=Date.now()-Number(state.analysis?.receivedAt||0);if(!state.analysis||!state.live){badge.textContent="INDISPONÍVEL";badge.title="Sem leitura e fluxo válidos";}else if(state.live.stale||age>15000){badge.textContent="ATRASADO";badge.title=`Leitura gerada há ${Math.max(0,Math.round(age/1000))} s`;}else{badge.textContent="AO VIVO";badge.title=`Leitura gerada há ${Math.max(0,Math.round(age/1000))} s`;}}
function updatePixel(){const signal=state.analysis?.signal||"AGUARDE",pixel=$("pixel");pixel.className=`pixel-wrap ${signal==="COMPRA"?"mood-up":signal==="VENDA"?"mood-down":"mood-flat"}`;$("pixelTip").textContent=signal==="COMPRA"?"hum… compradores acordaram":signal==="VENDA"?"cuidado, pressão vendedora":"mercado pensando; eu também";}
function renderPlan(p){if(!p){$("riskPlan").innerHTML=`<p class="legal">Sinal em espera: não há plano de entrada até existir confluência suficiente.</p>`;return;}const values=[["Entrada",fmt(p.entry,8)],["Stop técnico",fmt(p.stop,8)],["Alvo 1",fmt(p.target1,8)],["Alvo 2",fmt(p.target2,8)],["Risco/retorno",Number.isFinite(Number(p.riskReward2))?`1:${fmt(p.riskReward2,2)}`:"--"],["Qtd. ref.",fmt(p.suggestedQuantity,8)]];$("riskPlan").innerHTML=values.map(([l,v])=>`<div class="risk-card"><span>${l}</span><b>${esc(v)}</b></div>`).join("")+`${p.invalidation?`<p class="legal"><b>Invalidação:</b> ${esc(p.invalidation)}</p>`:""}${p.note?`<p class="legal">${esc(p.note)}</p>`:""}`;}
function renderLevels(levels={}){const group=(title,rows,cls)=>`<div class="level-group"><h3 class="${cls}">${title}</h3>${(rows||[]).map(x=>`<div class="level-row"><span>${fmt(x.price,8)}</span><small>${x.touches} toques · força ${fmt(x.strength,2)} · ${fmt(x.distancePct,2)}%</small></div>`).join("")||"<small>Sem nível forte próximo.</small>"}</div>`,vp=levels.volumeProfile||{};$("levels").innerHTML=group("SUPORTES",levels.supports,"positive")+group("RESISTÊNCIAS",levels.resistances,"negative")+`<div class="level-group"><h3>VOLUME POR PREÇO</h3><div class="level-row"><span>POC</span><small>${fmt(vp.poc,8)}</small></div><div class="level-row"><span>Área de valor</span><small>${fmt(vp.valueAreaLow,8)} – ${fmt(vp.valueAreaHigh,8)}</small></div></div>`;}

function drawingKey(){return `dieftrade.drawings.${state.symbol}`;}
function loadDrawings(){try{state.chartDrawings=JSON.parse(localStorage.getItem(drawingKey())||"[]").filter(item=>["horizontal","trend"].includes(item.type)).slice(-80);}catch{state.chartDrawings=[];}}
function saveDrawings(){localStorage.setItem(drawingKey(),JSON.stringify(state.chartDrawings.slice(-80)));}
function setChartTool(tool){state.chartTool=state.chartTool===tool?null:tool;state.chartDraft=null;$("chartHorizontal").classList.toggle("tool-active",state.chartTool==="horizontal");$("chartTrend").classList.toggle("tool-active",state.chartTool==="trend");toast(state.chartTool==="horizontal"?"Clique no preço para marcar um nível":state.chartTool==="trend"?"Clique em dois pontos para traçar a tendência":"Ferramenta de desenho encerrada");requestChart();}
function clearDrawings(){state.chartDrawings=[];state.chartDraft=null;saveDrawings();requestChart();toast("Desenhos do par removidos");}
function chartPoint(event){const m=state.chartMetrics,box=$("chart").getBoundingClientRect();if(!m)return null;const x=event.clientX-box.left,y=event.clientY-box.top;if(x<m.pad.l||x>m.w-m.pad.r||y<m.pad.t||y>m.h-m.pad.b)return null;return{x,y,price:m.max-(y-m.pad.t)/m.ch*m.range,t:m.firstT+(x-m.pad.l)/m.cw*(m.lastT-m.firstT)};}
function chartPointerDown(event){const chart=$("chart"),point=chartPoint(event);if(state.chartTool&&point){if(state.chartTool==="horizontal"){state.chartDrawings.push({type:"horizontal",price:point.price,createdAt:Date.now()});saveDrawings();toast(`Nível marcado em ${fmt(point.price,8)}`);}else if(!state.chartDraft){state.chartDraft={type:"trend",a:{t:point.t,price:point.price}};toast("Primeiro ponto marcado; escolha o segundo");}else{state.chartDrawings.push({type:"trend",a:state.chartDraft.a,b:{t:point.t,price:point.price},createdAt:Date.now()});state.chartDraft=null;saveDrawings();toast("Linha de tendência criada");}requestChart();return;}state.chartDrag={x:event.clientX,offset:state.chartOffset};chart.setPointerCapture?.(event.pointerId);}
function chartPointerMove(event){const chart=$("chart"),box=chart.getBoundingClientRect();state.chartCrosshair={x:event.clientX-box.left,y:event.clientY-box.top};if(state.chartTool){requestChart();return;}if(state.chartDrag&&state.chartMetrics){const step=Math.max(2,state.chartMetrics.cw/state.chartMetrics.count),moved=Math.round((event.clientX-state.chartDrag.x)/step);setChartView(state.chartDrag.offset+moved,state.chartZoom,false);}else requestChart();}

function drawChart(){
  const canvas=$("chart"),wrap=canvas.parentElement,a=state.analysis,confirmed=a?.series?.candles||[],provisional=state.provisionalCandle,lastConfirmed=confirmed.at(-1),all=provisional&&Number(provisional.t)>Number(lastConfirmed?.t||0)?[...confirmed,provisional]:confirmed; if(!all.length)return; const dpr=devicePixelRatio||1,w=wrap.clientWidth,h=wrap.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);
  const end=Math.max(1,all.length-state.chartOffset),start=Math.max(0,end-state.chartZoom),candles=all.slice(start,end),count=candles.length,pad={l:12,r:82,t:12,b:74},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b;const highs=candles.map(c=>Number(c.high)),lows=candles.map(c=>Number(c.low)),rawMax=Math.max(...highs),rawMin=Math.min(...lows),margin=Math.max((rawMax-rawMin)*.06,rawMax*1e-6),max=rawMax+margin,min=rawMin-margin,range=Math.max(max-min,1e-9),y=v=>pad.t+(max-v)/range*ch,x=i=>pad.l+(i+.5)/count*cw,bar=Math.max(1,cw/count*.62),firstT=Number(candles[0]?.t||0),lastT=Number(candles.at(-1)?.t||firstT+1),xTime=t=>pad.l+(Number(t)-firstT)/Math.max(1,lastT-firstT)*cw;state.chartMetrics={cw,ch,count,pad,w,h,start,end,min,max,range,firstT,lastT};
  ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue("--line")||"#14271b";ctx.fillStyle=getComputedStyle(document.body).getPropertyValue("--muted")||"#6e8176";ctx.font="10px Segoe UI";for(let i=0;i<6;i++){const yy=pad.t+i*ch/5;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();const val=max-i*range/5;ctx.fillText(fmt(val,val>100?2:6),w-pad.r+8,yy+3)}
  for(let i=0;i<5;i++){const idx=Math.min(count-1,Math.round(i*(count-1)/4)),xx=x(idx),date=new Date(Number(candles[idx]?.t||0)),time=state.interval==="1d"?date.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit",year:"2-digit"}):date.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});ctx.fillStyle=getComputedStyle(document.body).getPropertyValue("--muted")||"#6e8176";ctx.fillText(time,Math.max(pad.l,Math.min(w-pad.r-50,xx-22)),h-4);}
  const volMax=Math.max(...candles.map(c=>c.volume),1),volumeBase=h-30;candles.forEach((c,i)=>{const xx=x(i),up=c.close>=c.open,color=up?"#2eea7b":"#ff5e6c";ctx.fillStyle=up?"#2eea7b25":"#ff5e6c25";const vh=Math.min(38,c.volume/volMax*38);ctx.fillRect(xx-bar/2,volumeBase-vh,bar,vh);ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(xx,y(c.high));ctx.lineTo(xx,y(c.low));ctx.stroke();ctx.fillStyle=color;const top=y(Math.max(c.open,c.close)),bottom=y(Math.min(c.open,c.close));ctx.fillRect(xx-bar/2,top,bar,Math.max(1,bottom-top));});
  const drawLine=(values,color)=>{const arr=(values||[]).slice(start,end);ctx.strokeStyle=color;ctx.lineWidth=1.25;ctx.beginPath();let started=false;arr.forEach((v,i)=>{if(!Number.isFinite(v))return;const xx=x(i),yy=y(v);if(!started){ctx.moveTo(xx,yy);started=true}else ctx.lineTo(xx,yy)});ctx.stroke()};drawLine(a.series.ema9,"#ffcb52");drawLine(a.series.ema20,"#35e083");drawLine(a.series.ema50,"#6b8cff");drawLine(a.series.vwap,"#ca6bff");
  ctx.save();ctx.font="9px Segoe UI";for(const [rows,color,label] of [[a.levels?.supports,"#24d87888","S"],[a.levels?.resistances,"#ff5e6c88","R"]])for(const level of (rows||[]).slice(0,3)){const yy=y(Number(level.price));if(yy<pad.t||yy>h-pad.b)continue;ctx.setLineDash([4,5]);ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.fillStyle=color;ctx.fillText(`${label} ${fmt(level.price,6)}`,pad.l+5,yy-3);}ctx.setLineDash([]);for(const item of state.chartDrawings){ctx.strokeStyle="#ffd45d";ctx.lineWidth=1.5;if(item.type==="horizontal"){const yy=y(Number(item.price));if(yy>=pad.t&&yy<=h-pad.b){ctx.beginPath();ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();}}else{ctx.beginPath();ctx.moveTo(xTime(item.a.t),y(item.a.price));ctx.lineTo(xTime(item.b.t),y(item.b.price));ctx.stroke();}}if(state.chartDraft&&state.chartCrosshair){ctx.setLineDash([5,4]);ctx.strokeStyle="#ffd45d";ctx.beginPath();ctx.moveTo(xTime(state.chartDraft.a.t),y(state.chartDraft.a.price));ctx.lineTo(state.chartCrosshair.x,state.chartCrosshair.y);ctx.stroke();}ctx.restore();
  const last=candles.at(-1),lastY=y(last.close),up=last.close>=last.open,lastColor=up?"#18d873":"#ff5e6c";ctx.setLineDash([5,4]);ctx.strokeStyle=lastColor;ctx.beginPath();ctx.moveTo(pad.l,lastY);ctx.lineTo(w-pad.r,lastY);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=lastColor;ctx.fillRect(w-pad.r+3,lastY-10,pad.r-6,20);ctx.fillStyle="#061009";ctx.font="bold 10px Segoe UI";ctx.fillText(fmt(last.close,last.close>100?2:6),w-pad.r+7,lastY+4);
  const tip=$("chartTooltip"),cross=state.chartCrosshair;if(cross&&cross.x>=pad.l&&cross.x<=w-pad.r&&cross.y>=pad.t&&cross.y<=h-pad.b){const idx=Math.max(0,Math.min(count-1,Math.floor((cross.x-pad.l)/cw*count))),c=candles[idx],xx=x(idx),yy=Math.max(pad.t,Math.min(h-pad.b,cross.y)),hoverPrice=max-(yy-pad.t)/ch*range;ctx.setLineDash([3,4]);ctx.strokeStyle="#93aa9b88";ctx.beginPath();ctx.moveTo(xx,pad.t);ctx.lineTo(xx,h-pad.b);ctx.moveTo(pad.l,yy);ctx.lineTo(w-pad.r,yy);ctx.stroke();ctx.setLineDash([]);tip.style.display="block";tip.style.left=`${Math.min(w-225,Math.max(8,xx+12))}px`;tip.style.top=`${Math.max(8,Math.min(h-86,yy-42))}px`;tip.innerHTML=`<b>${new Date(Number(c.t)).toLocaleString("pt-BR")}</b><span>A ${fmt(c.open,8)} · M ${fmt(c.high,8)}</span><span>m ${fmt(c.low,8)} · F ${fmt(c.close,8)}</span><span>Cursor ${fmt(hoverPrice,8)}</span>`;}else tip.style.display="none";
}

function paperPrice(){return Number(state.live?.ticker?.last||state.analysis?.price);}
function expiryLabel(ms){if(ms>=60000)return `${Math.round(ms/60000)} min`;return `${Math.round(ms/1000)} s`;}
function countdown(ms){const total=Math.max(0,Math.ceil(Number(ms)/1000)),m=Math.floor(total/60),s=total%60;return `${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;}
function updateOrderPreview(){if(!$("orderPreview"))return;const stake=Number($("paperQty").value),price=paperPrice(),duration=Number($("paperExpiry").value);if(!(stake>0)||!(price>0)){$("orderPreview").textContent="Escolha se o preço estará acima ou abaixo ao terminar o tempo.";return;}const direction=state.side==="buy"?"acima":"abaixo",profit=stake*Number(state.paper?.payoutRate||.82);$("orderPreview").textContent=`${money(stake)} em ${state.symbol.replace("USDT","/USDT")}: você vence se o preço terminar ${direction} de ${priceFormat(price)} após ${expiryLabel(duration)}. Lucro no acerto: ${money(profit)}.`;}
async function submitPaper(e){e.preventDefault();const button=e.submitter||e.currentTarget.querySelector('[type="submit"]'),stake=Number($("paperQty").value),price=paperPrice(),durationMs=Number($("paperExpiry").value),idempotencyKey=crypto.randomUUID(),signal=state.analysis?.signalLifecycle;$("paperMessage").textContent="";button.disabled=true;try{if(!(stake>=1)||!(price>0))throw new Error("Informe um valor a partir de US$ 1 e aguarde o preço ao vivo.");if(stake>(state.paper?.balance||0))throw new Error(`Saldo virtual insuficiente. Disponível: ${money(state.paper?.balance||0)}.`);const out=await api("/api/paper/order",{method:"POST",body:JSON.stringify({symbol:state.symbol,direction:state.side==="buy"?"up":"down",stake,durationMs,interval:state.interval,note:$("paperNote").value,idempotencyKey,signalId:signal?.signalId||null,analysisId:state.analysis?.id||null})});state.paper=out.portfolio;renderPaper();const confirmedAt=Number(out.confirmedEntryPriceAt)>0?new Date(Number(out.confirmedEntryPriceAt)).toLocaleTimeString("pt-BR"):"agora";$("paperMessage").textContent=`Entrada confirmada em ${priceFormat(out.confirmedEntryPrice)} às ${confirmedAt}; resultado em ${expiryLabel(durationMs)}${out.trade.signalId?` · sinal ${out.trade.signalId.slice(0,8)}`:""}.`;toast(`Entrada demo confirmada em ${priceFormat(out.confirmedEntryPrice)}`);}catch(error){$("paperMessage").textContent=error.message;toast(error.message,true);}finally{button.disabled=false;}}
function notifyPaperResult(result){toast(result.result==="win"?`Acerto: +${money(result.profit)}`:result.result==="draw"?"Empate: valor devolvido":result.result==="unresolved"?"Cotação de encerramento indisponível; valor devolvido.":`Perda: ${money(Math.abs(result.profit))}`,result.result==="loss");}
function paperSignature(p){return JSON.stringify([p?.updatedAt,p?.balance,p?.realized,p?.open?.map(x=>[x.id,x.status,x.currentPrice]),p?.results?.[0]?.id]);}
async function refreshPaper(){try{const latest=await api("/api/paper"),signature=paperSignature(latest),previous=state.lastResultId,unseen=[];for(const result of latest.results||[]){if(result.id===previous)break;unseen.push(result);}if(latest.results?.[0])state.lastResultId=latest.results[0].id;unseen.reverse().forEach(notifyPaperResult);state.paper=latest;if(signature!==state.paperSignature){state.paperSignature=signature;renderPaper();}else updatePaperCountdowns();}catch(error){console.warn("Falha ao atualizar simulador:",error.message);}}
function updatePaperCountdowns(){document.querySelectorAll("[data-expires-at]").forEach(el=>{const remaining=Math.max(0,Number(el.dataset.expiresAt)-Date.now());el.textContent=remaining>0?countdown(remaining):"LIQUIDANDO";});}
async function resetPaper(){if(!confirm("Apagar todo o histórico do simulador e restaurar US$ 10.000?"))return;try{state.paper=await api("/api/paper/reset",{method:"POST",body:JSON.stringify({confirm:true})});state.lastResultId="__empty__";renderPaper();$("paperMessage").textContent="Saldo restaurado para US$ 10.000.";toast("Simulador restaurado");}catch(error){toast(error.message,true);}}
async function savePaperSettings(){try{state.paper=await api("/api/paper/settings",{method:"POST",body:JSON.stringify({payoutRate:Number($("paperPayout").value)})});renderPaper();toast("Retorno demo atualizado");}catch(error){toast(error.message,true);}}
async function exportPaper(){try{const response=await fetch("/api/paper/export",{headers:{"X-Dief-Token":state.token}});if(!response.ok)throw new Error("Não foi possível exportar o histórico.");const complete=response.headers.get("x-dief-history-complete")!=="0",unavailable=Number(response.headers.get("x-dief-history-unavailable")||0),blob=await response.blob(),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="historico-dieftrade.csv";document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(link.href),1000);toast(complete?"Histórico completo exportado":`Exportação concluída, mas ${unavailable} registro(s) antigo(s) já não estavam disponíveis.`,!complete);}catch(error){toast(error.message,true);}}
function renderPaper(){const p=state.paper;if(!p)return;$("cash").textContent=money(p.balance);$("equity").textContent=money(p.locked);$("paperReturn").textContent=money(p.realized);$("paperReturn").className=p.realized>=0?"positive":"negative";$("realized").textContent=`${fmt(p.winRate,1)}% · ${p.wins||0}V/${p.losses||0}D${p.draws?` · ${p.draws}E`:""}${p.unresolved?` · ${p.unresolved} devolvida(s)`:""}`;$("payoutRate").textContent=`${Math.round(Number(p.payoutRate||.82)*100)}%`;$("paperPayout").value=String(Number(p.payoutRate||.82).toFixed(2));$("profitFactor").textContent=p.profitFactor==null?"∞":fmt(p.profitFactor,2);$("expectancy").textContent=money(p.expectancy);$("maxDrawdown").textContent=`${fmt(p.maxDrawdown,2)}%`;$("currentStreak").textContent=p.currentStreak>0?`${p.currentStreak} acertos`:p.currentStreak<0?`${Math.abs(p.currentStreak)} perdas`:"neutra";$("learningSamples").textContent=state.analysis?.calibration?.samples??state.calibration?.samples??0;$("positions").innerHTML=(p.open||[]).map(x=>`<div class="list-row trade-open"><span><b class="${x.direction==="up"?"positive":"negative"}">${x.direction==="up"?"▲ ALTA":"▼ BAIXA"}</b> ${esc(x.symbol)}<small> · ${money(x.stake)}</small><br><small>Entrada ${fmt(x.entryPrice,8)} · Agora ${fmt(x.currentPrice,8)}${x.note?` · ${esc(x.note)}`:""}</small></span><strong class="countdown" data-expires-at="${Number(x.expiresAt)}">${x.remainingMs>0?countdown(x.remainingMs):"LIQUIDANDO"}</strong></div>`).join("")||`<p class="legal">Nenhuma operação em andamento. Escolha Alta ou Baixa para começar.</p>`;$("trades").innerHTML=(p.results||[]).slice(0,50).map(t=>`<div class="list-row"><span><b class="${t.result==="win"?"positive":t.result==="loss"?"negative":""}">${t.result==="win"?"GANHOU":t.result==="loss"?"PERDEU":t.result==="unresolved"?"DEVOLVIDA":"EMPATE"}</b> ${esc(t.symbol)}<small> · ${t.direction==="up"?"ALTA":"BAIXA"}${t.analysisSnapshot?.signal?` · painel ${esc(t.analysisSnapshot.signal)}`:""}${t.note?` · ${esc(t.note)}`:""}${t.settlementReason?` · ${esc(t.settlementReason)}`:""}</small></span><small class="${t.profit>=0?"positive":"negative"}">${t.profit>=0?"+":""}${money(t.profit)}<br>${fmt(t.entryPrice,8)} → ${fmt(t.exitPrice,8)}</small></div>`).join("")||`<p class="legal">Seus resultados aparecerão aqui ao terminar o tempo.</p>`;updateOrderPreview();drawPaperEquity();}
function drawPaperEquity(){const canvas=$("equityChart"),rows=state.paper?.equityCurve||[];if(!canvas||!rows.length)return;const box=canvas.parentElement,dpr=devicePixelRatio||1,w=box.clientWidth,h=box.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const values=rows.map(x=>Number(x.value)),min=Math.min(...values),max=Math.max(...values),range=Math.max(1,max-min),x=i=>12+i/Math.max(1,rows.length-1)*(w-24),y=v=>12+(max-v)/range*(h-24);ctx.strokeStyle="#35e083";ctx.lineWidth=2;ctx.beginPath();rows.forEach((row,i)=>i?ctx.lineTo(x(i),y(row.value)):ctx.moveTo(x(i),y(row.value)));ctx.stroke();ctx.lineTo(w-12,h-10);ctx.lineTo(12,h-10);ctx.closePath();ctx.fillStyle="#35e08318";ctx.fill();ctx.fillStyle=getComputedStyle(document.body).getPropertyValue("--muted")||"#789083";ctx.font="10px Segoe UI";ctx.fillText(money(max),12,12);ctx.fillText(money(min),12,h-5);}
async function submitAlert(e){e.preventDefault();const button=e.submitter||e.currentTarget.querySelector('[type="submit"]');button.disabled=true;try{const item=await api("/api/alerts",{method:"POST",body:JSON.stringify({symbol:state.symbol,interval:state.interval,kind:$("alertKind").value,value:Number($("alertValue").value),note:$("alertNote").value})});state.alerts.unshift(item);renderAlerts();toast("Alerta criado");}catch(error){toast(error.message,true);}finally{button.disabled=false;}}
function updateAlertValue(){const kind=$("alertKind").value,needsValue=["price_gte","price_lte","confidence_gte"].includes(kind);$("alertValueLabel").style.display=needsValue?"block":"none";$("alertValue").required=needsValue;$("alertValue").placeholder=kind==="confidence_gte"?"Ex.: 70":"Preço-alvo";}
function alertDescription(a){if(a.kind==="price_gte")return `preço ≥ ${fmt(a.value,8)}`;if(a.kind==="price_lte")return `preço ≤ ${fmt(a.value,8)}`;if(a.kind==="signal_buy")return `novo sinal COMPRA confirmado em ${a.interval}`;if(a.kind==="signal_sell")return `novo sinal VENDA confirmado em ${a.interval}`;return `leitura ativa com qualidade ≥ ${fmt(a.value,0)}% em ${a.interval}`;}
function renderAlerts(){$("alertsList").innerHTML=state.alerts.map(a=>`<div class="list-row"><span><b class="${a.active?"":"positive"}">${esc(a.symbol)}</b><small> ${esc(alertDescription(a))}${a.active?"":" · DISPARADO"}${a.note?` · ${esc(a.note)}`:""}</small></span><button type="button" class="danger" aria-label="Excluir alerta" data-alert="${a.id}">×</button></div>`).join("")||`<p class="legal">Nenhum alerta configurado.</p>`;$("alertsList").querySelectorAll("[data-alert]").forEach(b=>b.onclick=async()=>{try{await api(`/api/alerts/${b.dataset.alert}`,{method:"DELETE"});state.alerts=state.alerts.filter(x=>x.id!==b.dataset.alert);renderAlerts();}catch(error){toast(error.message,true);}});}
function notifyAlert(alert){toast(`Alerta ${alert.symbol}: ${alertDescription(alert)}${alert.note?` · ${alert.note}`:""}`);if(preferences().alertSound===false)return;try{const audio=new AudioContext(),osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.value=880;gain.gain.setValueAtTime(.09,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.32);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.33);}catch(error){console.warn("Som de alerta indisponível:",error.message);}}
async function submitJournal(e){e.preventDefault();const button=e.submitter||e.currentTarget.querySelector('[type="submit"]');button.disabled=true;try{await api("/api/journal",{method:"POST",body:JSON.stringify({symbol:state.symbol,interval:state.interval,setup:$("journalSetup").value,note:$("journalNote").value,side:"observe"})});$("journalSetup").value="";$("journalNote").value="";await loadJournal({offset:0});toast("Anotação salva");}catch(error){toast(error.message,true);}finally{button.disabled=false;}}
async function loadJournal({offset=state.journalPage.offset,query=state.journalPage.query}={}){try{const page=await api(`/api/journal?offset=${Math.max(0,offset)}&limit=${state.journalPage.limit}&q=${encodeURIComponent(query||"")}`);state.journal=page.items||[];state.journalPage={...state.journalPage,...page};renderJournal();}catch(error){toast(error.message,true);}}
function renderJournal(){$("journalList").innerHTML=state.journal.map(j=>`<div class="list-row"><span><b>${esc(j.symbol)}</b> ${esc(j.setup||"Observação")}<small> ${new Date(j.createdAt).toLocaleString("pt-BR")}${j.note?` · ${esc(j.note)}`:""}</small></span><button type="button" class="danger" aria-label="Excluir anotação" data-journal="${j.id}">×</button></div>`).join("")||`<p class="legal">Nenhuma anotação encontrada.</p>`;const p=state.journalPage,start=p.total?Math.min(p.total,p.offset+1):0,end=Math.min(p.total,p.offset+state.journal.length);$("journalPageInfo").textContent=`${start}–${end} de ${p.total}`;$("journalPrev").disabled=p.offset<=0;$("journalNext").disabled=!p.hasMore;$("journalList").querySelectorAll("[data-journal]").forEach(b=>b.onclick=async()=>{try{await api(`/api/journal/${b.dataset.journal}`,{method:"DELETE"});await loadJournal({offset:state.journal.length===1?Math.max(0,p.offset-p.limit):p.offset});}catch(error){toast(error.message,true);}});}
async function saveAi(e){e.preventDefault();try{const key=$("aiKey").value.trim(),provider=$("aiProvider").value;if(!key)throw new Error("Cole uma chave nova.");const result=await api("/api/ai/config",{method:"POST",body:JSON.stringify({apiKey:key,provider,model:$("aiModel").value.trim()}),timeoutMs:42000});$("aiKey").value="";$("aiStatus").textContent=result.migrationRequired?"⚠ Chave preservada, mas a migração para Auth AQ. é necessária.":`✓ Geração estruturada validada · ${result.provider==="gemini"?"Gemini":"OpenAI"} · ${result.model}`;toast(result.migrationRequired?"Chave salva; migração necessária":"Chave salva e geração validada",result.migrationRequired);}catch(error){$("aiStatus").textContent=error.message;toast(error.message,true);}}
async function removeAi(){try{await api("/api/ai/config",{method:"DELETE"});$("aiStatus").textContent="Chave removida.";toast("Chave de IA removida");}catch(error){toast(error.message,true);}}
async function diagnoseAi(showToast=true){const b=$("aiTest");b.disabled=true;try{const result=await api("/api/ai/test",{method:"POST",body:"{}",timeoutMs:42000});const stages=Object.entries(result.stages||{}).map(([name,status])=>`${name.toUpperCase()} ${status==="ok"?"✓":"…"}`).join(" · ");$("aiStatus").textContent=`IA OPERACIONAL · ${result.displayName||result.model} · ${result.latencyMs} ms · ${stages}`;if(showToast)toast("Geração estruturada validada de ponta a ponta");return result;}catch(error){$("aiStatus").textContent=`Falha no diagnóstico: ${error.message}`;if(showToast)toast(error.message,true);throw error;}finally{b.disabled=false;}}
async function testAi(){try{await diagnoseAi(true);}catch{}}
async function readAi(){const b=$("aiRead"),symbol=state.symbol,interval=state.interval,analysis=state.analysis,generation=++state.aiGeneration,started=Date.now();b.disabled=true;const progress=setInterval(()=>{if(generation===state.aiGeneration)$("aiResult").textContent=`Preparando e validando a leitura complementar… ${Math.round((Date.now()-started)/1000)} s`;},1000);$("aiResult").textContent="Validando o retrato exato exibido…";try{if(!analysis?.id)throw new Error("Atualize a leitura antes de pedir a IA.");const out=await api("/api/ai/read",{method:"POST",body:JSON.stringify({analysisId:analysis.id,symbol,interval}),timeoutMs:42000});if(generation===state.aiGeneration&&symbol===state.symbol&&interval===state.interval){const meta=`${out.context.symbol.replace("USDT","/USDT")} · ${out.context.interval}\nAnálise: ${new Date(out.context.analysisCalculatedAt).toLocaleTimeString("pt-BR")} · IA: ${new Date(out.context.generatedAt).toLocaleTimeString("pt-BR")}\nModelo: ${out.provider}/${out.model} · Request: ${out.requestId||"não informado"}\nAnalysis ID: ${out.context.analysisId}${out.context.signalId?` · Signal ID: ${out.context.signalId}`:""}`;$("aiResult").textContent=`${meta}\n\n${formatAi(out.content)}`;}}catch(error){if(generation===state.aiGeneration)$("aiResult").textContent=`Não foi possível gerar a leitura: ${error.message}`;}finally{clearInterval(progress);if(generation===state.aiGeneration)b.disabled=false;}}
function formatAi(v){if(typeof v==="string")return v;const format=value=>Array.isArray(value)?value.map(item=>typeof item==="object"?JSON.stringify(item):String(item)).join(" · "):value&&typeof value==="object"?JSON.stringify(value,null,2):String(value??"");return Object.entries(v||{}).map(([key,value])=>`${key.replace(/_/g," ").toUpperCase()}: ${format(value)}`).join("\n\n");}
bootstrap();
