"use strict";

const { AppError } = require("./contracts.cjs");
const { JsonStore } = require("./storage.cjs");
const { createAdapter, providerError } = require("./ai-adapters.cjs");

const REQUIRED_FIELDS = ["veredito", "resumo", "contexto", "confirmacoes", "conflitos", "riscos", "gatilho", "invalidacao", "gerenciamento"];
const LIST_FIELDS = new Set(["confirmacoes", "conflitos", "riscos"]);
const AI_SCHEMA = { type: "object", additionalProperties: false, properties: { veredito: { type: "string", enum: ["COMPRA", "VENDA", "AGUARDE"] }, resumo: { type: "string" }, contexto: { type: "string" }, confirmacoes: { type: "array", items: { type: "string" } }, conflitos: { type: "array", items: { type: "string" } }, riscos: { type: "array", items: { type: "string" } }, gatilho: { type: "string" }, invalidacao: { type: "string" }, gerenciamento: { type: "string" } }, required: REQUIRED_FIELDS };
const DIAGNOSTIC_PAYLOAD = { id: "diagnostic-snapshot", symbol: "BTCUSDT", interval: "1m", calculatedAt: 1, marketDataAgeMs: 0, signal: "AGUARDE", score: 0, confidence: 0, reasons: [], warnings: ["Diagnóstico técnico sem operação."], dataQuality: { score: 100 }, multiTimeframe: { status: "ready", coverage: 100, alignment: 0, signal: "AGUARDE" }, signalLifecycle: { status: "NEUTRAL", direction: null } };

function extractText(response) { if (typeof response?.output_text === "string") return response.output_text; return (response?.output || []).flatMap((item) => item.content || []).map((content) => content.text).filter((value) => typeof value === "string").join("\n"); }
function extractGeminiText(response) { return (response?.candidates || []).flatMap((candidate) => candidate.content?.parts || []).map((part) => part.text).filter((value) => typeof value === "string").join("\n"); }
function extractJsonObject(text) { const source = String(text || "").trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim(); if (!source) return ""; try { JSON.parse(source); return source; } catch {} let start = -1, depth = 0, inString = false, escaped = false; for (let index = 0; index < source.length; index += 1) { const char = source[index]; if (inString) { if (escaped) escaped = false; else if (char === "\\") escaped = true; else if (char === '"') inString = false; continue; } if (char === '"') { inString = true; continue; } if (char === "{") { if (depth === 0) start = index; depth += 1; } else if (char === "}" && depth > 0) { depth -= 1; if (depth === 0 && start >= 0) return source.slice(start, index + 1); } } return source; }
function cleanText(value, field) { if (typeof value !== "string") throw new AppError(`A resposta da IA não contém texto válido em ${field}.`, { status: 502, code: "AI_INVALID_RESPONSE" }); const clean = value.trim().slice(0, 2400); if (!clean) throw new AppError(`A resposta da IA deixou ${field} vazio.`, { status: 502, code: "AI_INVALID_RESPONSE" }); return clean; }
function parseJson(text) { const clean = extractJsonObject(text); if (!clean) throw new AppError("A IA retornou uma resposta vazia.", { status: 502, code: "AI_EMPTY_RESPONSE" }); let parsed; try { parsed = JSON.parse(clean); } catch (cause) { throw new AppError("A IA retornou uma resposta incompleta. Tente novamente.", { status: 502, code: "AI_INVALID_JSON", cause }); } if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new AppError("A IA retornou um formato inesperado.", { status: 502, code: "AI_INVALID_RESPONSE" }); const normalized = {}; for (const field of REQUIRED_FIELDS) { if (!(field in parsed)) throw new AppError(`A resposta da IA não contém o campo obrigatório ${field}.`, { status: 502, code: "AI_INVALID_RESPONSE" }); if (LIST_FIELDS.has(field)) { if (!Array.isArray(parsed[field])) throw new AppError(`O campo ${field} precisa ser uma lista.`, { status: 502, code: "AI_INVALID_RESPONSE" }); normalized[field] = parsed[field].slice(0, 12).map((item) => cleanText(item, field)); } else normalized[field] = cleanText(parsed[field], field); } normalized.veredito = normalized.veredito.toUpperCase(); if (!["COMPRA", "VENDA", "AGUARDE"].includes(normalized.veredito)) throw new AppError("A IA retornou veredito inválido.", { status: 502, code: "AI_INVALID_VERDICT" }); return normalized; }

function violatesGuarantee(content) {
  const text = Object.values(content || {}).flatMap((value) => Array.isArray(value) ? value : [value]).join(". ").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  const safe = text.replace(/nao (?:ha|existe|e) (?:qualquer )?(?:certeza|operacao sem risco)/g, "").replace(/(?:lucro|resultado) (?:nao e|nao esta) garantid[oa]/g, "").replace(/nao (?:ha|existe) lucro certo/g, "");
  return /(?:lucro|retorno|resultado)\s+(?:e\s+)?garantid[oa]|(?:voce\s+)?certamente\s+(?:ganhara|lucra|vence)|operacao\s+sem\s+risco|100\s*%\s+de\s+certeza|lucro\s+certo/i.test(safe);
}
function enforceVerdict(engine, ai) { if (engine === "AGUARDE" && ai !== "AGUARDE") return false; if (engine === "COMPRA" && ai === "VENDA") return false; if (engine === "VENDA" && ai === "COMPRA") return false; return true; }
function containsInventedFutureTime(content, confirmedAt = null) { const found = [...JSON.stringify(content).matchAll(/(?:as|às)\s+(\d{1,2}):(\d{2})(?::(\d{2}))?/gi)]; if (!found.length) return false; if (!confirmedAt) return true; const expected = new Date(Number(confirmedAt)).toLocaleTimeString("pt-BR", { hour12: false }); return found.some((match) => !expected.startsWith(`${match[1].padStart(2, "0")}:${match[2]}`)); }
function combinedSignal(external, timeoutMs) { const timeout = AbortSignal.timeout(timeoutMs); if (!external) return timeout; return typeof AbortSignal.any === "function" ? AbortSignal.any([external, timeout]) : timeout; }
const telemetryInitial = () => ({ lastDiagnostic: null, lastGeneration: null, updatedAt: Date.now() });
const TELEMETRY_FIELDS = new Set(["ok", "operational", "generationValidated", "provider", "model", "displayName", "phase", "errorCode", "requestId", "analysisId", "latencyMs", "retries", "supportsGenerateContent", "stages", "at"]);
const validTelemetryRecord = (value) => value == null || Boolean(value && typeof value === "object" && !Array.isArray(value) && Object.keys(value).every((key) => TELEMETRY_FIELDS.has(key)) && (!value.stages || (typeof value.stages === "object" && !Array.isArray(value.stages) && Object.entries(value.stages).every(([key, stage]) => ["auth", "model", "generation", "structuredJson", "schema", "parser", "guardrail"].includes(key) && ["pending", "ok", "failed"].includes(stage)))) && !JSON.stringify(value).match(/api.?key|authorization|bearer|AQ\.|AIza|sk-/i));
const validTelemetry = (value) => Boolean(value && typeof value === "object" && !Array.isArray(value) && Object.keys(value).every((key) => ["lastDiagnostic", "lastGeneration", "updatedAt"].includes(key)) && validTelemetryRecord(value.lastDiagnostic) && validTelemetryRecord(value.lastGeneration) && Number.isFinite(Number(value.updatedAt)));

class AiReader {
  constructor(credentialStore, { cooldownMs = 5000, dailyLimit = 100, requestTimeoutMs = 18000, monotonic = () => performance.now(), now = () => Date.now(), dataDirectory = null } = {}) {
    this.credentials = credentialStore; this.cooldownMs = cooldownMs; this.dailyLimit = dailyLimit; this.requestTimeoutMs = requestTimeoutMs; this.monotonic = monotonic; this.now = now; this.lastRequestMono = -Infinity; this.day = null; this.dailyCalls = 0; this.pending = false; this.telemetryStore = dataDirectory ? new JsonStore(dataDirectory, "ai-telemetry.json", telemetryInitial, { validate: validTelemetry }) : null;
  }
  #telemetry(kind, value) { if (!this.telemetryStore) return; this.telemetryStore.value[kind] = { ...value, at: this.now() }; this.telemetryStore.value.updatedAt = this.now(); this.telemetryStore.saveQueued(); }
  telemetry() { return this.telemetryStore ? structuredClone(this.telemetryStore.value) : telemetryInitial(); }
  assertReady() { const day = new Date(this.now()).toISOString().slice(0, 10); if (this.day !== day) { this.day = day; this.dailyCalls = 0; } if (this.pending) throw new AppError("Já existe uma leitura de IA em andamento.", { status: 409, code: "AI_BUSY" }); const remaining = this.cooldownMs - (this.monotonic() - this.lastRequestMono); if (remaining > 0) throw new AppError(`Aguarde ${Math.ceil(remaining / 1000)} segundo(s) antes de pedir outra leitura.`, { status: 429, code: "AI_COOLDOWN" }); if (this.dailyCalls >= this.dailyLimit) throw new AppError(`Limite local diário de ${this.dailyLimit} leituras atingido.`, { status: 429, code: "AI_DAILY_LIMIT" }); const status = this.credentials.status?.(); if (status && !status.operational && status.stored) throw new AppError(status.error || "A chave protegida não está operacional.", { status: 503, code: "AI_CREDENTIAL_UNAVAILABLE" }); }
  #consume() { this.lastRequestMono = this.monotonic(); this.dailyCalls += 1; }
  async #request(url, options, context, { attempts = 2, timeoutMs = this.requestTimeoutMs } = {}) { let lastError; for (let attempt = 0; attempt < attempts; attempt += 1) { try { const response = await fetch(url, { ...options, signal: combinedSignal(options.signal, timeoutMs) }); if (response.ok) return response; const error = providerError({ ...context, status: response.status, body: await response.text().catch(() => "") }); if (error.code !== "AI_UNAVAILABLE" || attempt === attempts - 1) throw error; lastError = error; } catch (error) { if (options.signal?.aborted) throw new AppError("A leitura foi cancelada.", { status: 499, code: "AI_CANCELLED" }); if (error?.name === "TimeoutError" || error?.name === "AbortError") lastError = new AppError("A IA demorou demais para responder. Tente novamente em instantes.", { status: 504, code: "AI_TIMEOUT", cause: error }); else lastError = error instanceof AppError ? error : new AppError("Não foi possível conectar ao provedor de IA.", { status: 503, code: "AI_NETWORK", cause: error }); if (attempt === attempts - 1 || !["AI_UNAVAILABLE", "AI_TIMEOUT", "AI_NETWORK"].includes(lastError.code)) throw lastError; } await new Promise((resolve) => setTimeout(resolve, 250 * (attempt + 1))); } throw lastError; }
  #adapter() { const { apiKey, provider = "openai", model } = this.credentials.load(); if (!apiKey) throw new AppError("Configure uma chave de IA nas preferências.", { status: 409, code: "AI_NOT_CONFIGURED" }); return createAdapter({ provider, apiKey, model, request: this.#request.bind(this) }); }
  #instructions() { return ["Você é o Dief, assistente técnico educacional de day trade de criptomoedas.", "Use somente o JSON fornecido. Não invente notícias, preços, probabilidade, lucro, certeza nem horários.", "A entidade signalLifecycle é determinística: explique-a, mas nunca crie ou inverta um sinal.", "Você pode ser mais conservador e responder AGUARDE.", "Responda em português do Brasil. Não faça promessa, recomendação financeira nem instrução automática."].join(" "); }
  #payload(payload) { return { analysisId: payload.id, symbol: payload.symbol, interval: payload.interval, price: payload.price, calculatedAt: payload.calculatedAt, latestCandleCloseTime: payload.latestCandleCloseTime, marketDataAgeMs: payload.marketDataAgeMs, microDataAgeMs: payload.microDataAgeMs, signal: payload.signal, singleTimeframeSignal: payload.singleTimeframeSignal, score: payload.score, confidence: payload.confidence, regime: payload.regime, reasons: payload.reasons || [], warnings: payload.warnings || [], indicators: payload.indicators || {}, levels: payload.levels || {}, micro: payload.micro || {}, multiTimeframe: payload.multiTimeframe || null, plan: payload.plan || null, dataQuality: payload.dataQuality || null, calibration: payload.calibration || null, signalLifecycle: payload.signalLifecycle || null }; }
  async read(payload, { signal } = {}) { this.assertReady(); const adapter = this.#adapter(); const started = this.monotonic(); this.pending = true; try { const generated = await adapter.generateStructured({ instructions: this.#instructions(), payload: this.#payload(payload), schema: AI_SCHEMA, signal }); const content = parseJson(generated.text); if (violatesGuarantee(content)) throw new AppError("A resposta da IA fez uma promessa indevida e foi descartada.", { status: 422, code: "AI_GUARDRAIL" }); if (!enforceVerdict(payload.signal, content.veredito)) throw new AppError("A IA contrariou o sinal determinístico do painel e a resposta foi descartada.", { status: 422, code: "AI_SIGNAL_CONTRACT" }); if (containsInventedFutureTime(content, payload.signalLifecycle?.confirmedAt)) throw new AppError("A IA inventou um horário que não pertence ao sinal confirmado.", { status: 422, code: "AI_INVENTED_TIME" }); this.#consume(); const result = { mode: adapter.provider, provider: adapter.provider, model: adapter.model, content, context: { analysisId: payload.id, signalId: payload.signalLifecycle?.signalId || null, symbol: payload.symbol, interval: payload.interval, analysisCalculatedAt: payload.calculatedAt, marketDataAgeMs: payload.marketDataAgeMs, generatedAt: this.now() }, requestId: generated.requestId || null }; this.#telemetry("lastGeneration", { ok: true, provider: adapter.provider, model: adapter.model, requestId: result.requestId, analysisId: payload.id, latencyMs: Math.round(this.monotonic() - started), retries: 0 }); return result; } catch (error) { this.#telemetry("lastGeneration", { ok: false, provider: adapter.provider, model: adapter.model, phase: error.code || "generation", errorCode: error.code || "AI_UNKNOWN", latencyMs: Math.round(this.monotonic() - started) }); throw error; } finally { this.pending = false; } }
  async diagnose({ signal } = {}) { const adapter = this.#adapter(); const started = this.monotonic(); const stages = { auth: "pending", model: "pending", generation: "pending", structuredJson: "pending", schema: "pending", parser: "pending", guardrail: "pending" }; try { const model = await adapter.validateModel({ signal }); stages.auth = "ok"; stages.model = "ok"; const generated = await adapter.generateStructured({ instructions: `${this.#instructions()} Isto é um diagnóstico: responda AGUARDE e descreva apenas que o contrato funciona.`, payload: DIAGNOSTIC_PAYLOAD, schema: AI_SCHEMA, signal, maxOutputTokens: 500 }); stages.generation = "ok"; if (!extractJsonObject(generated.text)) throw new AppError("A geração respondeu sem JSON estruturado.", { status: 502, code: "AI_DIAG_STRUCTURED_JSON" }); stages.structuredJson = "ok"; const parsed = parseJson(generated.text); stages.schema = "ok"; stages.parser = "ok"; if (violatesGuarantee(parsed) || !enforceVerdict("AGUARDE", parsed.veredito)) throw new AppError("A resposta de diagnóstico falhou no contrato de segurança.", { status: 422, code: "AI_DIAG_GUARDRAIL" }); stages.guardrail = "ok"; const result = { ok: true, operational: true, generationValidated: true, provider: adapter.provider, model: adapter.model, displayName: model.displayName, latencyMs: Math.round(this.monotonic() - started), supportsGenerateContent: true, requestId: generated.requestId || model.requestId || null, stages }; this.#telemetry("lastDiagnostic", result); return result; } catch (error) { const pending = Object.keys(stages).find((key) => stages[key] === "pending"); if (pending) stages[pending] = "failed"; const result = { ok: false, provider: adapter.provider, model: adapter.model, phase: pending || "unknown", errorCode: error.code || "AI_UNKNOWN", latencyMs: Math.round(this.monotonic() - started), stages }; this.#telemetry("lastDiagnostic", result); error.diagnostic = result; throw error; } }
  async flushPersistence() { await this.telemetryStore?.flush(); }
}

module.exports = { AiReader, AI_SCHEMA, extractText, extractGeminiText, extractJsonObject, parseJson, providerError, REQUIRED_FIELDS, violatesGuarantee, enforceVerdict, containsInventedFutureTime };
